# heavily 'inspired' by cfillions reapack/reaimgui

version: "{build}-{branch}"

before_build:
  - git submodule update --init --recursive --depth 1
build_script:
  - export VCPKG_OVERLAY_TRIPLETS=cmake/vcpkg-triplets
  - cmake -B build -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake
    -DVCPKG_TARGET_TRIPLET=arch-env -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$TOOLCHAIN
    -DCMAKE_OSX_ARCHITECTURES=$ARCH -DCMAKE_OSX_DEPLOYMENT_TARGET=$DEPLOY_TARGET
  - cmake --build build

test_script:
  - '[ "$ARCH" = "arm64" ] || ctest -C Release --test-dir build --output-on-failure'

for:
  - matrix: { only: [appveyor_build_worker_image: &linux Ubuntu2004] }
    cache:
      - build/vcpkg_installed -> vcpkg.json, cmake/vcpkg-triplets/arch-env.cmake
    install: |-
      set -e

      sudo sed -i '/arch=/! s/^deb/deb [arch=amd64,i386]/' /etc/apt/sources.list
      awk '
      $3 !~ /ubuntu\.com/ { next }
      $1 == "deb" {
        $2 = "[arch=armhf,arm64]";
        $3 = "http://ports.ubuntu.com/ubuntu-ports/"
      } 1' /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list > /dev/null

      install-deps() {
        local arch="$1"; shift
        local native=("$@" php-cli qemu-user-binfmt)
        local target=(
          libboost-dev libcurl4-openssl-dev libsqlite3-dev libssl-dev
          libxml2-dev zlib1g-dev
        )

        sudo dpkg --add-architecture $arch
        sudo apt-get update -qq
        sudo apt-get install -qq aptitude > /dev/null
        sudo aptitude install -yR ${native[@]} ${target[@]/%/:$arch} > /dev/null
      }

      sudo update-alternatives --set gcc /usr/bin/gcc-9

      case $ARCH in
      x86_64)
        install-deps amd64
        ;;
      i686)
        install-deps i386 g++-multilib
        export TOOLCHAIN=$(pwd)/cmake/linux-cross.cmake \
               TOOLCHAIN_PREFIX=i386-linux-gnu
        ;;
      armv7l)
        install-deps armhf g++-arm-linux-gnueabihf
        export TOOLCHAIN=$(pwd)/cmake/linux-cross.cmake \
               TOOLCHAIN_PREFIX=arm-linux-gnueabihf
        ;;
      aarch64)
        install-deps arm64 g++-aarch64-linux-gnu
        export TOOLCHAIN=$(pwd)/cmake/linux-cross.cmake \
               TOOLCHAIN_PREFIX=aarch64-linux-gnu
        ;;
      esac
    artifacts:
      - path: build/reaper_*.so

  - matrix: { only: [ appveyor_build_worker_image: macos-monterey, appveyor_build_worker_image: macos-bigsur ] }
    cache:
      - build/vcpkg_installed -> vcpkg.json, cmake/vcpkg-triplets/arch-env.cmake
    install:
      - |-
        case $ARCH in
        arm64)  
          export MACOSX_DEPLOYMENT_TARGET=11.0 XCODE_VERSION=14.1
          ;;
        x86_64) 
          export MACOSX_DEPLOYMENT_TARGET=10.9 XCODE_VERSION=13.2.1
          ;;
        esac
      - sudo xcode-select -s /Applications/Xcode-$XCODE_VERSION.app
      # https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
      - sudo curl -k https://curl.se/ca/cacert.pem -o /etc/ssl/cert.pem
    artifacts:
      - path: build/reaper_*.dylib

  - matrix: { only: [appveyor_build_worker_image: &windows Visual Studio 2022] }
    cache:
      - build\vcpkg_installed -> vcpkg.json
    install:
      - if "%ARCH%" == "x64" call "%ProgramFiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
      - if "%ARCH%" == "x86" call "%ProgramFiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"

    build_script:
      - cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DVCPKG_TARGET_TRIPLET=%ARCH%-windows-static
        -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake
      - cmake --build build
    artifacts:
      - path: build\reaper_*.dll

environment:
  matrix:
    - job_name: Linux ARM 64-bit
      appveyor_build_worker_image: *linux
      ARCH: aarch64
    - job_name: Linux ARM 32-bit
      appveyor_build_worker_image: *linux
      ARCH: armv7l
    - job_name: macOS ARM 64-bit
      appveyor_build_worker_image: macos-monterey
      ARCH: arm64
    - job_name: macOS x86 64-bit
      appveyor_build_worker_image: macos-bigsur
      ARCH: x86_64
    - job_name: Linux x86 64-bit
      appveyor_build_worker_image: *linux
      ARCH: x86_64
    - job_name: Linux x86 32-bit
      appveyor_build_worker_image: *linux
      ARCH: i686
    - job_name: Windows 64-bit
      appveyor_build_worker_image: *windows
      ARCH: x64
    - job_name: Windows 32-bit
      appveyor_build_worker_image: *windows
      ARCH: x86

deploy:
  provider: GitHub
  draft: true
  description: ""
  force_update: true
  auth_token:
    secure: o55HSvCnXfZ+Ghcswts4Oq0qyAaVR/QkvzGzXzvtriSg5I9iOZr9d21MfJsA0/5Q
  artifact: /.*\.(dll|dylib|so|lua)/
  on:
    APPVEYOR_REPO_TAG: true
